language: python
python: "3.7"
sudo: required
dist: xenial
install: make requirements
script: make tox

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.6
