dist: xenial
sudo: required
install: make requirements
script: make tox

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial main'
    packages:
      - python3.5-dev
      - python3.6-dev
      - python3.7-dev
